### ISSUE TITLE
Xdebug is not installed in PHP image

### ISSUE THREAD

**Issue by johnpbloch** [10up/Docker-Images#1]
It would be good to have for local development. What are the chances of getting this built in?

**Comment by ericmann** [comment]
If we do add it, we'll need to add a way to enable/disable it programmatically. Any ideas?

**Comment by ericmann** [comment]
``` sh
&& pecl install xdebug && echo "extension=$(php -i | grep -P '^extension_dir' | sed -r -e 's/.+=> (.+) =>.+/\1/')/xdebug.so" > $PHP_INI_DIR/conf.d/ext-xdebug.ini \
&& echo xdebug.remote_enable=1 > $PHP_INI_DIR/conf.d/ext-xdebug.ini \
&& echo xdebug.remote_connect_back=1 > $PHP_INI_DIR/conf.d/ext-xdebug.ini \
&& echo xdebug.idekey=PHPSTORM > $PHP_INI_DIR/conf.d/ext-xdebug.ini \
```

inserting the above between lines 98 and 99 of the PHP Dockerfile will install and enable XDebug

**Comment by johnpbloch** [comment]
I should add that I made a slight mistake when concocting those commands, and the 2nd through 4th lines should use `>>` when redirecting output, not `>`.

**Comment by tlovett1** [comment]
@ericmann @johnpbloch how do we envision programmatically controlling xdebug?

**Comment by ericmann** [comment]
Closing for now, though we might revisit in the future.
